[package]
name = "ping"
version = "0.1.0-beta"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
reqwest = "0.13.1"
tokio = { version = "1.48.0", features = ["full"] }
